import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faHouse,
  faGem,
  faReceipt,
  faCalendarDays,
  faScrewdriverWrench,
  faBullseye,
  faShieldHalved,
  faGear,
  faUsers,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faPlus,
  faPen,
  faTrash,
  faXmark,
  faCheck,
  faArrowUp,
  faArrowDown,
  faCircleExclamation,
  faTriangleExclamation,
  faClock,
  faLock,
  faLockOpen,
  faArrowRotateLeft,
  faBars,
  faSun,
  faMoon,
  faCircleHalfStroke,
  faRightFromBracket,
  faKey,
  faEllipsisVertical,
  faFolder,
  faChartLine,
  faMoneyBillWave,
  faWallet,
  faPiggyBank,
  faCreditCard,
  faCoins,
  faSackDollar,
  faHandHoldingDollar,
  faCircleInfo,
  faCircleCheck,
  faCircleXmark,
  faChartPie,
  faThumbTack,
  faWandSparkles,
  faFileInvoiceDollar,
  faArrowsRotate,
  faFloppyDisk,
  faDownload,
  faUpload,
  faFilter,
  faSort,
  faGripVertical,
  faEye,
  faEyeSlash,
  faCaretDown,
  faCaretUp,
  faArrowTrendUp,
  faArrowTrendDown,
} from '@fortawesome/free-solid-svg-icons';

import {
  faCircle as farCircle,
  faSquare as farSquare,
  faSquareCheck as farSquareCheck,
  faCalendar as farCalendar,
  faClock as farClock,
  faStar as farStar,
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faHouse, faGem, faReceipt, faCalendarDays, faScrewdriverWrench,
  faBullseye, faShieldHalved, faGear, faUsers, faChevronDown,
  faChevronRight, faChevronLeft, faPlus, faPen, faTrash, faXmark,
  faCheck, faArrowUp, faArrowDown, faCircleExclamation,
  faTriangleExclamation, faClock, faLock, faLockOpen,
  faArrowRotateLeft, faBars, faSun, faMoon, faCircleHalfStroke,
  faRightFromBracket, faKey, faEllipsisVertical, faFolder,
  faChartLine, faMoneyBillWave, faWallet, faPiggyBank,
  faCreditCard, faCoins, faSackDollar, faHandHoldingDollar,
  faCircleInfo, faCircleCheck, faCircleXmark, faChartPie,
  faThumbTack, faWandSparkles, faFileInvoiceDollar, faArrowsRotate,
  faFloppyDisk, faDownload, faUpload, faFilter, faSort,
  faGripVertical, faEye, faEyeSlash, faCaretDown, faCaretUp,
  faArrowTrendUp, faArrowTrendDown,
  farCircle, farSquare, farSquareCheck, farCalendar, farClock, farStar
);
